# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtCore import Qt, QPointF, QDateTime,QTime
from PyQt5.QtGui import QPainter
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QChartView, QLineSeries, QLogValueAxis, QValueAxis,QDateTimeAxis

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 900)
        MainWindow.setStyleSheet("#MainWindow{border-image:url(img/background)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        '''数据可视化'''
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(950, 10, 300, 200))
        self.listView.setObjectName("listView")
        self.listView.setStyleSheet("QListView{background-color:rgba(135,135,135,200)}"
                                      "QListView{border:none")
        self.label_A = QtWidgets.QLabel(self.centralwidget)
        self.label_A.setGeometry(QtCore.QRect(950, 10, 300, 50))
        self.label_A.setObjectName("listView_2")
        self.label_A.setText("项目概况")
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setStyleSheet("QLabel{font-size:30px}"
                                   "QLabel{font-weight:500}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_B = QtWidgets.QLabel(self.centralwidget)
        self.label_B.setGeometry(QtCore.QRect(955, 58, 256, 50))
        self.label_B.setObjectName("listView_2")
        self.label_B.setAlignment(QtCore.Qt.AlignTop)
        self.label_B.setText("开发者:")
        self.label_B.setStyleSheet("QLabel{font-size:20px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.label_B_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_B_1.setGeometry(QtCore.QRect(1050, 58, 256, 50))
        self.label_B_1.setObjectName("listView_2")
        self.label_B_1.setAlignment(QtCore.Qt.AlignTop)
        self.label_B_1.setText("柠檬")
        self.label_B_1.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_C = QtWidgets.QLabel(self.centralwidget)
        self.label_C.setGeometry(QtCore.QRect(955, 88, 256, 50))
        self.label_C.setObjectName("listView_2")
        self.label_C.setAlignment(QtCore.Qt.AlignTop)
        self.label_C.setText("测试地点:")
        self.label_C.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_C_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_C_1.setGeometry(QtCore.QRect(1050, 88, 256, 50))
        self.label_C_1.setObjectName("listView_2")
        self.label_C_1.setAlignment(QtCore.Qt.AlignTop)
        self.label_C_1.setText("人工智能学院")
        self.label_C_1.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_D = QtWidgets.QLabel(self.centralwidget)
        self.label_D.setGeometry(QtCore.QRect(955, 118, 256, 50))
        self.label_D.setObjectName("listView_2")
        self.label_D.setAlignment(QtCore.Qt.AlignTop)
        self.label_D.setText("项目简介:")
        self.label_D.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_D_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_D_1.setGeometry(QtCore.QRect(1050, 118, 200, 100))
        self.label_D_1.setObjectName("listView_2")
        self.label_D_1.setAlignment(QtCore.Qt.AlignTop)
        self.label_D_1.setWordWrap(True)
        self.label_D_1.setText("使用Zigbee采集教室温湿度并显示在界面，并且还有课堂考勤功能，智能AI为你清点人数。")
        self.label_D_1.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")

        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(950, 230, 300, 200))
        self.listView_2.setObjectName("listView_2")
        self.listView_2.setStyleSheet("QListView{background-color:rgba(135,135,135,200)}"
                                      "QListView{border:none")
        self.listView_2_hour_min = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_hour_min.setGeometry(QtCore.QRect(950, 220, 200, 100))
        self.listView_2_hour_min.setObjectName("label_list")
        self.listView_2_hour_min.setAlignment(QtCore.Qt.AlignCenter)
        self.listView_2_hour_min.setStyleSheet("QLabel{font-size:70px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.listView_2_mon_day = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_mon_day.setGeometry(QtCore.QRect(1150, 230, 100, 50))
        self.listView_2_mon_day.setObjectName("label_list")
        self.listView_2_mon_day.setStyleSheet("QLabel{font-size:30px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_2_year = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_year.setGeometry(QtCore.QRect(1160, 260, 100, 50))
        self.listView_2_year.setObjectName("label_list")
        self.listView_2_year.setStyleSheet("QLabel{font-size:30px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_2_yingdao = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_yingdao.setGeometry(QtCore.QRect(960, 300, 100, 50))
        self.listView_2_yingdao.setObjectName("listView_2_yingdao")
        self.listView_2_yingdao.setText("应到：")
        self.listView_2_yingdao.setStyleSheet("QLabel{font-size:30px}"
                                           "QLabel{font-weight:100}"
                                           "QLabel{font-family:楷体}"
                                           "QLabel{color:k}")
        self.listView_2_yingdao_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_yingdao_label.setGeometry(QtCore.QRect(1050, 300, 100, 50))
        self.listView_2_yingdao_label.setObjectName("listView_2_yingdao_label")
        self.listView_2_yingdao_label.setText("50")
        self.listView_2_yingdao_label.setStyleSheet("QLabel{font-size:30px}"
                                              "QLabel{font-weight:100}"
                                              "QLabel{font-family:楷体}"
                                              "QLabel{color:k}")
        self.listView_2_shidao = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_shidao.setGeometry(QtCore.QRect(960, 340, 100, 50))
        self.listView_2_shidao.setText("实到：")
        self.listView_2_shidao.setObjectName("listView_2_shidao")
        self.listView_2_shidao.setStyleSheet("QLabel{font-size:30px}"
                                           "QLabel{font-weight:100}"
                                           "QLabel{font-family:楷体}"
                                           "QLabel{color:k}")
        self.listView_2_shidao_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_shidao_label.setGeometry(QtCore.QRect(1050, 340, 130, 50))
        self.listView_2_shidao_label.setText("实到人数")
        self.listView_2_shidao_label.setObjectName("listView_2_shidao_label")
        self.listView_2_shidao_label.setStyleSheet("QLabel{font-size:30px}"
                                             "QLabel{font-weight:100}"
                                             "QLabel{font-family:楷体}"
                                             "QLabel{color:k}")
        self.listView_2_queqin = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_queqin.setGeometry(QtCore.QRect(960, 380, 100, 50))
        self.listView_2_queqin.setText("缺勤：")
        self.listView_2_queqin.setObjectName("listView_2_queqin")
        self.listView_2_queqin.setStyleSheet("QLabel{font-size:30px}"
                                             "QLabel{font-weight:100}"
                                             "QLabel{font-family:楷体}"
                                             "QLabel{color:k}")
        self.listView_2_queqin_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_2_queqin_label.setGeometry(QtCore.QRect(1050, 380, 130, 50))
        self.listView_2_queqin_label.setText("缺勤人数")
        self.listView_2_queqin_label.setObjectName("listView_2_queqin_label")
        self.listView_2_queqin_label.setStyleSheet("QLabel{font-size:30px}"
                                                   "QLabel{font-weight:100}"
                                                   "QLabel{font-family:楷体}"
                                                   "QLabel{color:k}")

        self.listView_3 = QtWidgets.QListView(self.centralwidget)
        self.listView_3.setGeometry(QtCore.QRect(950, 450, 300, 200))
        self.listView_3.setObjectName("listView_3")
        self.listView_3.setStyleSheet("QListView{background-color:rgba(135,135,135,200)}"
                                      "QListView{border:none")

        self.wdj_label = QtWidgets.QLabel(self.centralwidget)
        self.wdj_label.setGeometry(QtCore.QRect(990, 455, 80, 190))
        self.wdj_label.setObjectName("label_list")
        self.wdj_label.setPixmap(QtGui.QPixmap("img/wdj.jpg"))
        self.wdj_label.setScaledContents(True)
        self.wdj = QtWidgets.QProgressBar(self.centralwidget)
        self.wdj.setGeometry(QtCore.QRect(1022, 469, 15, 175))
        self.wdj.setObjectName("wdj")
        self.wdj.setMinimum(0)
        self.wdj.setMaximum(100)
        self.wdj.setValue(50)#滑块位置
        self.wdj.setOrientation(QtCore.Qt.Vertical)
        self.yujing = QtWidgets.QLabel(self.centralwidget)
        self.yujing.setGeometry(QtCore.QRect(1100, 575, 70, 70))
        self.yujing.setObjectName("label_list")
        self.yujing_1 = QtWidgets.QLabel(self.centralwidget)
        self.yujing_1.setGeometry(QtCore.QRect(1190, 575, 70, 70))
        self.yujing_1.setObjectName("label_list")
        self.yujing_1.setStyleSheet("QLabel{font-size:25px}"
                                            "QLabel{font-weight:100}"
                                            "QLabel{font-family:楷体}"
                                            "QLabel{color:k}")

        self.listView_3_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label.setGeometry(QtCore.QRect(1100, 450, 150, 50))
        self.listView_3_label.setObjectName("label_list")
        self.listView_3_label.setText('当前温度')
        self.listView_3_label.setStyleSheet("QLabel{font-size:30px}"
                                                   "QLabel{font-weight:100}"
                                                   "QLabel{font-family:楷体}"
                                                   "QLabel{color:k}")
        self.listView_3_label_10 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_10.setGeometry(QtCore.QRect(1100, 500, 100, 50))
        self.listView_3_label_10.setObjectName("label_list")
        self.listView_3_label_10.setText('摄氏度：')
        self.listView_3_label_10.setStyleSheet("QLabel{font-size:20px}"
                                              "QLabel{font-weight:100}"
                                              "QLabel{font-family:楷体}"
                                              "QLabel{color:k}")
        self.listView_3_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_11.setGeometry(QtCore.QRect(1175, 500, 100, 50))
        self.listView_3_label_11.setObjectName("label_list")
        self.listView_3_label_11.setText('0')
        self.listView_3_label_11.setStyleSheet("QLabel{font-size:20px}"
                                            "QLabel{font-weight:100}"
                                            "QLabel{font-family:楷体}"
                                            "QLabel{color:k}")
        self.listView_3_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_12.setGeometry(QtCore.QRect(1200, 500, 100, 50))
        self.listView_3_label_12.setObjectName("label_list")
        self.listView_3_label_12.setText('℃')
        self.listView_3_label_12.setStyleSheet("QLabel{font-size:20px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_3_label_20 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_20.setGeometry(QtCore.QRect(1100, 530, 100, 50))
        self.listView_3_label_20.setObjectName("label_list")
        self.listView_3_label_20.setText('华氏度：')
        self.listView_3_label_20.setStyleSheet("QLabel{font-size:20px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_3_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_21.setGeometry(QtCore.QRect(1175, 530, 100, 50))
        self.listView_3_label_21.setObjectName("label_list")
        self.listView_3_label_21.setText('0')
        self.listView_3_label_21.setStyleSheet("QLabel{font-size:20px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_3_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.listView_3_label_22.setGeometry(QtCore.QRect(1200, 530, 100, 50))
        self.listView_3_label_22.setObjectName("label_list")
        self.listView_3_label_22.setText('℉')
        self.listView_3_label_22.setStyleSheet("QLabel{font-size:20px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")

        self.listView_4 = QtWidgets.QListView(self.centralwidget)
        self.listView_4.setGeometry(QtCore.QRect(950, 670, 300, 200))
        self.listView_4.setObjectName("listView_4")
        self.listView_4.setStyleSheet("QListView{background-color:rgba(135,135,135,200)}"
                                      "QListView{border:none")

        self.listView_22_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_22_label.setGeometry(QtCore.QRect(970, 693, 150, 150))
        self.listView_22_label.setObjectName("label_list")
        self.listView_22_label.setPixmap(QtGui.QPixmap("img/sdj.jpg"))
        self.listView_22_label.setScaledContents(True)
        self.sdj = QtWidgets.QDial(self.centralwidget)
        self.sdj.setGeometry(QtCore.QRect(984, 710, 120, 120))
        self.sdj.setObjectName("sdj")
        self.sdj.setValue(0)#表盘的指针位置
        self.sdj.setMinimum(0)
        self.sdj.setMaximum(100)
        self.sdj.setNotchesVisible(True)
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setGeometry(QtCore.QRect(1000, 770, 150, 150))
        self.label_0.setObjectName("label_list")
        self.label_0.setText('0')
        self.label_0.setStyleSheet("QLabel{font-size:20px}"
                                    "QLabel{font-weight:100}"
                                    "QLabel{font-family:楷体}"
                                    "QLabel{color:k}")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(990, 622, 150, 150))
        self.label_40.setObjectName("label_list")
        self.label_40.setText('40')
        self.label_40.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(1110, 650, 150, 150))
        self.label_70.setObjectName("label_list")
        self.label_70.setText('70')
        self.label_70.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.label_100 = QtWidgets.QLabel(self.centralwidget)
        self.label_100.setGeometry(QtCore.QRect(1070, 770, 150, 150))
        self.label_100.setObjectName("label_list")
        self.label_100.setText('100')
        self.label_100.setStyleSheet("QLabel{font-size:20px}"
                                   "QLabel{font-weight:100}"
                                   "QLabel{font-family:楷体}"
                                   "QLabel{color:k}")
        self.listView_4_label = QtWidgets.QLabel(self.centralwidget)
        self.listView_4_label.setGeometry(QtCore.QRect(1120, 750, 150, 50))
        self.listView_4_label.setObjectName("label_list")
        self.listView_4_label.setText('当前湿度')
        self.listView_4_label.setStyleSheet("QLabel{font-size:30px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")
        self.listView_4_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.listView_4_label_11.setGeometry(QtCore.QRect(1160, 790, 100, 50))
        self.listView_4_label_11.setObjectName("label_list")
        self.listView_4_label_11.setText('0')
        self.listView_4_label_11.setStyleSheet("QLabel{font-size:30px}"
                                                   "QLabel{font-weight:100}"
                                                   "QLabel{font-family:楷体}"
                                                   "QLabel{color:k}")
        self.listView_4_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.listView_4_label_12.setGeometry(QtCore.QRect(1192, 790, 100, 50))
        self.listView_4_label_12.setObjectName("label_list")
        self.listView_4_label_12.setText('RH')
        self.listView_4_label_12.setStyleSheet("QLabel{font-size:30px}"
                                               "QLabel{font-weight:100}"
                                               "QLabel{font-family:楷体}"
                                               "QLabel{color:k}")

        '''列表'''
        self.label_list = QtWidgets.QLabel(self.centralwidget)
        self.label_list.setGeometry(QtCore.QRect(10, 10, 250, 860))
        self.label_list.setObjectName("label_list")
        self.label_list.setStyleSheet("QLabel{background-color:rgba(135,135,135,200)}"
                                      "QLabel{border:none")
        self.label_list_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_list_1.setGeometry(QtCore.QRect(10, 10, 250, 40))
        self.label_list_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_1.setObjectName("label_list_1")
        self.label_list_1.setStyleSheet("QLabel{background-color:rgba(98,94,96,200)}"
                                        "QLabel{border:none}"
                                        "QLabel{font-size:25px}"
                                       "QLabel{font-weight:100}"
                                       "QLabel{font-family:楷体}"
                                       "QLabel{color:k}")

        self.label_comboBox = QtWidgets.QLabel(self.centralwidget)
        self.label_comboBox.setGeometry(QtCore.QRect(30, 60, 90, 30))
        self.label_comboBox.setObjectName("label_comboBox")
        self.label_comboBox.setStyleSheet(
                                        "QLabel{font-size:25px}"
                                        "QLabel{font-weight:100}"
                                        "QLabel{font-family:楷体}"
                                        "QLabel{color:k}")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(125, 63, 110, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet(
                                        "QComboBox{font-size:20px}"
                                        "QComboBox{font-weight:100}"
                                        "QComboBox{font-family:楷体}"
                                        "QComboBox{color:k}")

        self.label_comboBox_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_comboBox_2.setGeometry(QtCore.QRect(30, 108, 90, 30))
        self.label_comboBox_2.setObjectName("label_comboBox_2")
        self.label_comboBox_2.setStyleSheet(
                                        "QLabel{font-size:25px}"
                                        "QLabel{font-weight:100}"
                                        "QLabel{font-family:楷体}"
                                        "QLabel{color:k}")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(125, 110, 110, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setStyleSheet(
                                        "QComboBox{font-size:20px}"
                                        "QComboBox{font-weight:100}"
                                        "QComboBox{font-family:楷体}"
                                        "QComboBox{color:k}")


        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 155, 100, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(137, 155, 100, 35))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")

        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(30, 205, 100, 25))
        self.label_class.setObjectName("label_lineEdit")
        self.label_class.setStyleSheet(
                                        "QLabel{font-size:25px}"
                                        "QLabel{font-weight:100}"
                                        "QLabel{font-family:楷体}"
                                        "QLabel{color:k}")
        self.lineEdit_class = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_class.setGeometry(QtCore.QRect(150, 205, 85, 30))
        self.lineEdit_class.setObjectName("lineEdit")
        self.lineEdit_class.setStyleSheet(
                                        "QLineEdit{font-size:25px}"
                                        "QLineEdit{font-weight:100}"
                                        "QLineEdit{font-family:楷体}"
                                        "QLineEdit{color:k}")

        self.pushButton_class_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_class_1.setGeometry(QtCore.QRect(30, 248, 100, 35))
        self.pushButton_class_1.setObjectName("pushButton_2")
        self.pushButton_class_1.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")
        self.pushButton_class_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_class_2.setGeometry(QtCore.QRect(137, 248, 100, 35))
        self.pushButton_class_2.setObjectName("pushButton_4")
        self.pushButton_class_2.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")

        self.pushButton_zxt_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zxt_1.setGeometry(QtCore.QRect(30, 298, 100, 35))
        self.pushButton_zxt_1.setObjectName("pushButton_2")
        self.pushButton_zxt_1.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")
        self.pushButton_zxt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zxt_2.setGeometry(QtCore.QRect(137, 298, 100, 35))
        self.pushButton_zxt_2.setObjectName("pushButton_4")
        self.pushButton_zxt_2.setStyleSheet(
                                        "QPushButton{font-size:20px}"
                                        "QPushButton{font-weight:100}"
                                        "QPushButton{font-family:楷体}"
                                        "QPushButton{color:k}")


        '''消息提示'''
        self.label_biaoti = QtWidgets.QLabel(self.centralwidget)
        self.label_biaoti.setGeometry(QtCore.QRect(280, 450, 650, 40))
        self.label_biaoti.setAlignment(QtCore.Qt.AlignCenter)
        self.label_biaoti.setObjectName("label_biaoti")
        self.label_biaoti.setStyleSheet("QLabel{background-color:rgba(98,94,96,200)}"
                                        "QLabel{border:none}"
                                        "QLabel{font-size:25px}"
                                        "QLabel{font-weight:100}"
                                        "QLabel{font-family:楷体}"
                                        "QLabel{color:k}"
                                        )

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 490, 650, 380))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setStyleSheet("QTextEdit{font-size:20px}"
                                       "QTextEdit{font-weight:100}"
                                       "QTextEdit{font-family:楷体}"
                                       "QTextEdit{color:k}")
        '''==============================================================================='''
        self.chartView_1 = QtWidgets.QLabel(self.centralwidget)
        self.chartView_1.setGeometry(QtCore.QRect(280, 490, 650, 380))
        self.chartView_1.setObjectName("chartView_2")
        self.chartView_1.setPixmap(QtGui.QPixmap("img/test.jpg"))
        self.chartView_1.setScaledContents(True)
        self.chartView_1.setHidden(True)

        '''==============================================================================='''
        '''摄像头显示'''
        self.label_img_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_img_1.setGeometry(QtCore.QRect(281, 9, 650, 40))
        self.label_img_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_1.setObjectName("label_img_1")
        self.label_img_1.setStyleSheet("QLabel{background-color:rgba(98,94,96,200)}"
                                       "QLabel{border:none}"
                                       "QLabel{font-size:25px}"
                                       "QLabel{font-weight:100}"
                                       "QLabel{font-family:楷体}"
                                       "QLabel{color:k}")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(281, 49, 650, 380))
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.label_img.setPixmap(QtGui.QPixmap("img/test.jpg"))
        self.label_img.setScaledContents(True)


        '''原始文件'''
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教室环境考勤系统"))
        self.label_biaoti.setText(_translate("MainWindow", "消息提示"))
        self.label_list_1.setText(_translate("MainWindow", "功能选项"))
        self.label_img_1.setText(_translate("MainWindow", "监控显示"))
        self.label_comboBox.setText(_translate("MainWindow", "串口号"))
        self.label_comboBox_2.setText(_translate("MainWindow", "波特率"))
        self.label_class.setText(_translate("MainWindow", "班级人数"))
        self.pushButton_4.setText(_translate("MainWindow", "关闭预警"))
        self.pushButton_2.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_class_1.setText(_translate("MainWindow", "修改人数"))
        self.pushButton_class_2.setText(_translate("MainWindow", "打开监控"))
        self.pushButton_zxt_1.setText(_translate("MainWindow", "开启图形"))
        self.pushButton_zxt_2.setText(_translate("MainWindow", "关闭图形"))
